swagger: '2.0'
info:
  title: Heracles API
  description: Avalon Blog Apis.
  version: 1.0.0
schemes:
  - http
basePath: /v1
produces:
  - application/json
paths:
  /blogs:
    get:
      summary: blog list
      description: To get blog list
      parameters:
        - $ref: '#/parameters/limit'
        - $ref: '#/parameters/page'
      tags:
        - blog
      responses:
        '200':
          description: blogs list
          schema:
            type: array
            items:
              $ref: '#/definitions/BlogResponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      summary: create blog
      description: create blog
      parameters:
          - name: blog
            in: body
            schema:
              $ref: '#/definitions/BlogRequest'
            required: true
      tags:
        - blog
      responses:
        '201':
          description: blog detail
          schema:
            $ref: '#/definitions/BlogResponse'
        default:
          description: Unexpected error
          schema:
            $ref: '#/definitions/Error'
  /blog/{blog_id}:
    parameters:
      - name: blog_id
        in: path
        required: true
        type: integer
    get:
      responses:
        200:
          description: blog info
          schema:
            $ref: '#/definitions/BlogResponse'
    delete:
      responses:
        200:
          description: delete blog
    put:
      parameters:
        - name: blog
          in: body
          required: true
          schema:
            $ref: '#/definitions/BlogRequest'
      responses:
        201:
          description: update blog
definitions:
  BlogRequest:
    type: object
    properties:
      title:
        type: string
      content:
        type: string
  BlogResponse:
    type: object
    properties:
      id:
        type: integer
      title:
        type: string
      content:
        type: string
      is_published:
        type: boolean
      date_created:
        type: string
        format: date-time
      date_modified:
        type: string
        format: date-time
  Error:
    type: object
    properties:
      error_code:
        type: string
        default: ''
      status:
        type: integer
      message:
        type: string
        default: ''
      errors:
        type: array
        items:
          $ref: '#/definitions/ErrorField'
        default: []
  ErrorField:
    type: object
    properties:
      code:
        type: string
      filed:
        type: string
      message:
        type: string
parameters:
  limit:
    name: limit
    in: query
    description: max records to return
    default: 20
    type: integer
    format: int32
    maximum: 1000
    minimum: 1
  page:
    name: page
    in: query
    description: page number
    default: 1
    type: integer
    format: int32
    maximum: 1000
    minimum: 0
